### PR TITLE
Add delete and edit tooltips to reminders view

### PR DESCRIPTION
**Pull request by NathanBnm**
I tried to add some tooltips to improve accessibility but they doesn't appear when I build the app. Any idea?

As this PR is incomplete I marked it as draft.

### CODE REVIEW

**Comment by NathanBnm** [comment]
@matfantinel do you have any ideas?

**Comment by matfantinel** [comment]
Hey @NathanBnm , sorry for the silence. I didn't have time to take a closer look at this.
I had tried to add the tooltips while developing, but couldn't. I did not spend much time researching, though. It might be worth to check if tooltips on other `Gtk.Button.from_icon_name`s work in another context or view.

**Comment by NathanBnm** [comment]
Well not a problem! Thanks for your reply, I'll check what I can do when I will have time.

**Comment by NathanBnm** [comment]
@matfantinel I probably had an issue with the app not correctly updated. It's working fine. **This PR is ready for review**

**Comment by matfantinel** [comment]
Great, thank you!

**Pull request merged**
