### PR TITLE
Add Travis CI file for automated tests

### PR DESCRIPTION
**Pull request by meisenzahl**

### CODE REVIEW

**Comment by NathanBnm** [comment]
@meisenzahl Adding the `travis.yml` file is not enough. @matfantinel you have to register in Travis CI too if you wan to use Continuous Integration. See the wiki here https://github.com/elementary/houston/wiki/Continuous-Integration

**Comment by meisenzahl** [comment]
@NathanBnm thanks for further instructions.

**Comment by NathanBnm** [comment]
@matfantinel any update on this?

**Comment by matfantinel** [comment]
Hi @NathanBnm , I haven't got the time to dive into this yet. Is anything else needed besides registering on Travis?

**Comment by NathanBnm** [comment]
I don't think so (except merging this PR). You can check the doc if you want.

**Pull request merged**
