### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous Icon IMO is not too aesthetically pleasing and perceivably small compared to other eOS icons.

### CODE REVIEW

**Comment by matfantinel** [comment]
Hey @Fatih20, thanks for the PR!

I like the shape of the head, and think it would be more recognizable than the current one.

However, I believe the eyes and beak are too simplified. For the eyes, something like the current one is just fine I believe. For the beak, I think it could be a little bit more realistic... But honestly I don't have the skills to do that.

**Comment by Fatih20** [comment]
I'll try to look into how to do that.

**Comment by Fatih20** [comment]
> Hey @Fatih20, thanks for the PR!
> 
> I like the shape of the head, and think it would be more recognizable than the current one.
> 
> However, I believe the eyes and beak are too simplified. For the eyes, something like the current one is just fine I believe. For the beak, I think it could be a little bit more realistic... But honestly I don't have the skills to do that.

After some consideration and testing, making a more realistic beak and eyes is possible, however, it's not favorable to do so because they are tend to be too small to be perceived effectively by the user.

**Comment by Fatih20** [comment]
So, anything that you think can be improved?

**Comment by matfantinel** [comment]
Hey @Fatih20 , sorry for the delay, been quite busy lately.
I have some ideas and will present them in this PR as soon as I got the time.

**Comment by matfantinel** [comment]
What do you think of something like this? (old vs new)

old_dock
new_dock
old_list
new_list

I think this is a bit more realistic than your proposal, but still more recognizable and visually appealing than the current one.

That being said, I think there are still some improvements to be made:
* A little "hair" on the top of its head like the current one would help with the shape not looking too much like a circle;
* The beak could use a wider stroke (easy to fix, I just didn't have the time right now);
* For smaller sizes (like the list one in the screenshot), we could have a separate version of the icon with a wider overall stroke and possibly bigger beak/eyes. Having different icons is not really uncommon.

**Comment by Fatih20** [comment]
That does look good, however, the color is not the best. I could fix those issues and my color issues if you send me the svg.

**Comment by Fatih20** [comment]
The feather wouldn't work. The size boundary would make adding feather reduce the size of the duck's head perceivably big, causing it to not be worth the downside. I found that ins small sizes, I would need to squint my eyes to recognize that it's a duckm so I revert to the previous icon because it's better perceived as a duck at small sizes.

**Comment by matfantinel** [comment]
Hey @Fatih20 , I played a bit with your file and got onto something that I think looks quite good.

image

image


Notice how it is a different icon on the small size, but it still has the same overall design. I made the beak, eyes and shape bigger/simpler to improve how recognizable it is.

I have a 1080p 14" secondary screen, which makes things look quite a bit small. Even with astigmatism, which makes my vision a bit blurry, and the icon is still recognizable for me.

On the dock, you can see its height is compatible with eOS's default apps. Notice how Files and Terminal seem to have different heights because of the folder's "tab" on top. Same applies for Reminduck's feather.

I think this result is quite good and hits a middle ground between realistic and cartoonish. Your entry was great, but too cartoony considering the default style. Mine is far from perfect, but is as far as my current skills can get to.

In any case, you helped **a lot** with your iterations and files. In fact, this result is just a slightly modified version of yours.

**Comment by Fatih20** [comment]
Okay then, make a commit and approve the changes.

**Pull request merged**
