### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by NathanBnm**
Here it is!

**This PR is ready for review**

### CODE REVIEW

**Comment by NathanBnm** [comment]
Note: I left the translation of "The duck that reminds you" fuzzy because the verb "to remind" is hard to translate in French and this is actually looking weird. In French it should be "to remind something". Maybe you'll have to edit the source string.

**Comment by NathanBnm** [comment]
If you want up to date translation. Please merge #24 before this. I'll fix the conflicts then.

**Comment by matfantinel** [comment]
Hey @NathanBnm , #24 was merged. There are no conflicts here. Do you still want to change something?

**Comment by NathanBnm** [comment]
Yes I have to split the `fr.po` files in two files like the other languages.

**Comment by NathanBnm** [comment]
@matfantinel you can merge this freely now :smile:

**Comment by matfantinel** [comment]
Marvelous. Will publish a new release today :D. Thank you!

**Pull request merged**
